require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe BackgroundsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Background. As you add validations to Background, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryBot.attributes_for :background
  end

  describe 'GET #index' do
    it 'returns a success response' do
      background = Background.create! valid_attributes
      get :index, params: {}
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      let(:current_user) { FactoryBot.create :user }
      before(:each) do
        request.headers.merge! current_user.create_new_auth_token
      end
      it 'creates a new Background' do
        expect do
          post :create, params: { background: valid_attributes }
        end.to change(Background, :count).by(1)
      end

      it 'renders a JSON response with the new background' do
        post :create, params: { background: valid_attributes }
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(background_url(Background.last))
      end
    end
  end

  describe 'DELETE #destroy' do
    let(:current_user) { FactoryBot.create :user }
    before(:each) do
      request.headers.merge! current_user.create_new_auth_token
    end
    it 'destroys the requested background' do
      background = Background.create! valid_attributes
      expect do
        delete :destroy, params: { id: background.to_param }
      end.to change(Background, :count).by(-1)
    end
  end

end
